### ISSUE TITLE
Reproduction question

### ISSUE THREAD

**Issue by LesterGong** [WenliangGuo/SCHEMA#2]
Hello! Thank you for such a surprising work.
However, when I follow your script (`lr=5e-3`, as described in your paper) on `CrossTask (T=3)`, I only get result:
```
SR=31.39%, Acc=56.52%, MIoU=77.6%
```

And for `NIV (T=4)`, I only get:
```
SR=21.88%, Acc=37.59%, MIoU=74.85%
```
I wonder if there is a problem.

**Comment by WenliangGuo** [comment]
Thank you for your interest in our work. 

The checkpoints we have provided are comparable to or even exceed the results reported in the paper. I think the possible reason for this issue is the difference in our platforms. We encountered the same problem in our evaluations. Our final results were obtained using a single V100 (32G) GPU, but when we tried to load the same checkpoint files on the server with an RTX Titan (24G) GPU, we couldn't get the same good results, for example, the success rate dropped by around 2% on CrossTask dataset.

My suggestion is that you can try to train from scratch and check the results. If you have any further questions about training, please do not hesitate to contact us. We are happy to discuss with you.
